### ISSUE TITLE
Release of version 1.1.0

### ISSUE THREAD

**Issue by Kokenberg** [microsoft/durabletask-mssql#135] opened 2023-01-03 10:06 UTC
The documentation states that as of version 1.1.0 it should be possible to use 'Isolated shema mode', a mode I really would like to use. 

![image](https://user-images.githubusercontent.com/15146247/210336111-9b253a1e-cfaa-4a61-8144-b7213049c007.png)

However, the 1.1.0 NuGet package is nowhere to be found! I did see that all the code of the PR has been merged to main:

![image](https://user-images.githubusercontent.com/15146247/210336303-851e580c-a390-4d3a-9966-d63dad4e5ad5.png)

Would it be possible to release the 1.1.0 version?

**Comment by jundayin** [comment] 2023-01-10 02:34
+1, we keep having issue with new team onboard their services using DTF and mess up the shared `dt` schema with the latest version of pacakge.

1.1.0 seems long way ahead (we are flipping one minor version from 1.0.1). Not sure about the roadmap

**Comment by jundayin** [comment] 2023-01-10 17:47
@Kokenberg As far as I can tell there are still two open issues for 1.1.0 milestone. [One is under review](https://github.com/microsoft/durabletask-mssql/issues/124) and another still awaits for implementation. @cgillum Is it possible to triage the latter one to next milestone so that we can consume this version faster?

**Comment by cgillum** [comment] 2023-01-10 18:13
Hi @jundayin and @Kokenberg. The only blocker at this point for v1.1.0 is the database upgrade testing PR, which unfortunately needs to be reworked a bit in order to be automated in GitHub Actions. However, we may not need to necessarily block the release on that. I've manually tested the upgrade scenario (going from v1.0.0 to v1.1.0) and I feel reasonably confident that automatically upgrading the database works correctly, even with in-flight orchestrations.

Just to help me feel confident about making the release, would either of you (or any other folks watching this issue) be willing to try out the [v1.1.0-rc release](https://github.com/microsoft/durabletask-mssql/releases/tag/v1.1.0-rc) that I just published this morning? If I can get confirmation that there are no issues with this upgrade, then that will give me the confidence to go ahead and publish a production-ready version of v1.1.0 this week.

**Comment by Kokenberg** [comment] 2023-01-11 13:57
I just tested the 1.1.0-RC and I can confirm that that the 'Isolated schema' works. I only updated the NuGet package and started the Durable Task. In Azure Data Studio I saw the new schema with tables appear:
![image](https://user-images.githubusercontent.com/15146247/211824631-ee545579-cce3-4e3c-a676-e47b3d20854a.png)

**Comment by cgillum** [comment] 2023-01-11 20:33
Thanks @Kokenberg!

@jundayin, do you have any availability to also try out the rc release bits?

**Comment by Kokenberg** [comment] 2023-01-13 08:47
@cgillum I just saw you merged the PR for running in dotnet-isolated. Any chance that that PR can also end up in the 1.1.0 release? That is also a feature we have been waiting for.

**Comment by cgillum** [comment] 2023-01-19 17:31
@Kokenberg unfortunately it turns the PR didn't work as intended (I merged it sooner than I should have). @jviau is going to help look into what additional fixes may be necessary, after which we can publish the new dotnet-isolated worker package.

**Closed** 2023-01-19 17:47 UTC

**Comment by jundayin** [comment] 2023-01-24 23:11
Hi, sorry. The notification was inundated by other emails.

I made a test and everything looks good. I created an orchestration 1.0.1 and re-start the program with update packages. The orchestration was picked up successfully and run without problem.

**Comment by cgillum** [comment] 2023-01-24 23:12
Thanks for confirming @jundayin - much appreciated!
