### ISSUE TITLE
NullReferenceException in SqlORchestrationService

### ISSUE THREAD

**Issue by gha-zund** [microsoft/durabletask-mssql#207] opened 2024-01-24 08:49 UTC
Hi there!

We currently are evaluating durabeltask-mssql since we are not happe with the default storage provider and Netherite seems to have issues with our scenario.

Thinks look good with mssql so far :)
But we have many exceptions in our log. We are not sure if this is a problem, since at the end of the message there is stated: 'Backing of for 1 seconds until 5 sucessful operations'. This sounds for me, like there is a retry mechanism which will resolve the problem.

Could you please confirm, that this exception can safely be ignored?
If so, would it be possible to catch this exception or prevent that it's logged?

Here the exception:

|                                  |                                                                                                                     |
|----------------------- |:-------------------------------------------------------------------------------:|
| Category                   | DurableTask.Core                                                                                        |
| Event name               | ProcessWorkItemFailed                                                                              |
| Formatted message  | TaskOrchestrationDispatcher-2d2b9b07130949b3a02e825caa30d54a-0: Unhandled exception with work item '@calculator@S300L160371': System.NullReferenceException: Object reference not set to an instance of an object.<br />at DurableTask.SqlServer.SqlOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in /_/src/DurableTask.SqlServer/SqlOrchestrationService.cs:line 342<br />at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 611<br />at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 211<br />at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in /_/src/DurableTask.Core/WorkItemDispatcher.cs:line 373<br /><br />Backing off for 1 seconds until 5 successful operations |

**Comment by gha-zund** [comment] 2024-01-24 12:27
I just realized that this exception always comes together with several warning logs (warnings come first).

|                     |                                                                                                                                            |
|--------------|:-----------------------------------------------------------------------------------------------:|
| Category     | DurableTask.Core                                                                                                                |
| Event name | DiscardingMessage                                                                                                            |
| message      | {entityId}: Discarding [EventRaised]: Received work-item for an invalid orchestration     |
| details         | Received work-item for an invalid orchestration                                                               |

**Comment by gha-zund** [comment] 2024-01-24 12:40
Ah, another info: we are using in-process functions, with .NET 6

**Comment by cgillum** [comment] 2024-01-24 18:19
Glad to hear that the MSSQL package is mostly working well for you. :)

The `NullReferenceException` makes me think there is a bug in our code that's somehow specific to `@calculator@S300L160371`. For example, maybe there's some unexpected or missing state in the database. Because this exception is going unhandled in the SQL provider code, it's resulting in throttling by the Durable Task Framework, which will impact the throughput of the entire VM.

I think we need to look at this more closely to understand what's causing the null-ref and try to fix it. Which versions of the DurableTask nuget packages are you using?

**Comment by cgillum** [comment] 2024-01-25 20:57
@gha-zund with the information you provided above, I was able to locate your Durable Entity instance and see this exception and the warnings you mentioned. I suspect that there's some error case that results in storing invalid state into the database. Corrupt state in the database will trigger the warning you're seeing, and I suspect that warning is what leads to the exception. 

I'm not sure if it's related to concurrency - the SQL backend has strong transactional consistency which should make it more resistant to state corruption. However, we can't completely rule it out yet.

To root cause this, I'll need to see what data you have in your database. Are you able to run the following query against your SQL database and share the results (feel free to scrub out any data that can't be shared publicly):

```sql
DECLARE @EntityID varchar(50) = '@calculator@S300L160371'
SELECT * FROM dt.Instances WHERE InstanceID = @EntityID
SELECT * FROM dt.History WHERE InstanceID = @EntityID
SELECT * FROM dt.NewEvents WHERE InstanceID = @EntityID
```

Ideally this would be captured when the errors are ongoing for a particular entity, and you can change the entity ID used in the query if needed. If the problem self-heals, then the result may not contain anything useful. The most important result would be the data in the `dt.History` table, which would give us a clue about whether there is corruption.

**Comment by gha-zund** [comment] 2024-01-25 21:06
Alright, thanks for the hints!

I fear the data will not be available anymore, since we purged all the history for all entities to get a clean state for further evaluation... 
The warnings did not occur the last 24h anymore, so maybe the problem is gone too.

We will keep the eyes open and provide the data in case the warnings appear again!

**Comment by cgillum** [comment] 2024-01-25 22:39
OK, no worries. I'll close this issue in the meantime but ping me if you see it again and we can reopen.

**Closed by cgillum** 2024-01-25 22:39 UTC
Labels: Needs: Attention :wave:
