### ISSUE TITLE
Lost Events

### ISSUE THREAD

**Issue by bhugot** [microsoft/durabletask-mssql#184] opened 2023-08-27 16:51 UTC
Hello,

I met an issue twice but i think it can be really hard to reproduce. I have an orchestration with 60k activities and a random number of events are lost (last time with around 14k with a mix of task id )
When I say lost it's that the activity has been done but there is no TaskCompleted row in history table for corresponding task.
This orchestration processed really slow like 36h were it take usually 10 min.
At the end the task and event was empty of any data but was missing those 14k TaskCompleted . 
To fix it i injected the missing rows in events and it fixed the orchestrations. 
I don't know if it the event table that was not filled or if the processing of the table lost it.

**Comment by cgillum** [comment] 2023-08-31 18:59
Hmm...I'm wondering how this might have happened. Just to make sure I understand, your orchestration schedules 60K activities and 14K (23%) of those activities weren't marked as completed in the history?

Were you able to see any warnings or errors in the logs around the time of the problem that might help explain what happened?

**Comment by bhugot** [comment] 2023-08-31 21:27
Sadly not I got it a few Time but didn t found anything related to this :(

**Comment by bhugot** [comment] 2023-09-06 16:11
Today I got the opposite 2 events for same task same orchestration. Deleted second event fixed the orchestration

**Comment by cgillum** [comment] 2023-09-19 20:40
@bhugot by chance are you running this app in Azure? If it's running as an Azure Functions app or an Azure Web App on the Azure App Service platform, we can find the telemetry to help us debug and determine what may have happened.

**Comment by bhugot** [comment] 2023-09-19 21:35
Yes we are on azure.

**Comment by cgillum** [comment] 2023-09-19 21:41
Are you on Azure App Service or Azure Functions? If so, can you let me know the instance ID of one of your orchestrations that had this problem, as well as an approximate time range and the Azure region? I can try to search for the telemetry. Unfortunately, I won't be able to find anything if you're running on VMs or AKS since we don't have telemetry collection for non-App Service platforms.

**Comment by bhugot** [comment] 2023-09-19 21:53
No it s on an azure functions. I should be able to give you those info tomorrow.

**Comment by bhugot** [comment] 2023-09-20 23:18
@cgillum so West Europe, one of this was stuck
| InstanceID | ExecutionID | CreatedTime | LastUpdatedTime |
|--------|--------|--------|--------|
| 54c09675d567446e8cbc3a5675802085:120 | e7100bbdecb049fa9f8cf6297cfc22f5 | 8/26/2023 8:58:57 AM | 8/26/2023 9:24:51 AM | 
| 54c09675d567446e8cbc3a5675802085:43  | 4de7da47dc6f4d1e9cb217c9fb283eaa | 8/26/2023 8:58:57 AM | 8/26/2023 9:16:41 AM | 
| 54c09675d567446e8cbc3a5675802085:76  | 1edd95c8e5094be7af9deff551937f20 | 8/26/2023 8:58:57 AM | 8/26/2023 9:39:37 AM |

**Comment by cgillum** [comment] 2023-11-07 18:28
Actually @bhugot, if you see this again in a more recent run, would you mind opening a support request with Azure? That would be really helpful for tracking and ensuring we get to the root cause quickly.

**Closed** 2023-11-17 02:59 UTC
Labels: Needs: Author Feedback, no-recent-activity, P1
